require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.dap"

-- Plugin config
require "user.alpha"
require "user.autopairs"
require "user.comment"
require "user.colorizer"
require "user.gitsigns"
require "user.impatient"
require "user.lualine"
require "user.neotest"
require "user.surround"
require "user.other"
require "user.project"
require "user.telescope"
require "user.toggleterm"
require "user.treesitter"
require "user.navic"
