[character]
success_symbol = "[❯](green)" # ❯
vicmd_symbol = "[\ue62b](green)" # 
error_symbol = "[\uf467](red)" # 

[package]
disabled = true

[username]
disabled = true

[hostname]
disabled = true

[aws]
disabled = true

[docker_context]
disabled = true

[git_branch]
# disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[git_metrics]
disabled = true

[git_status]
# disabled = true

[nodejs]
disabled = true
